# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87c1b0e8ecae7546a079dc7789dc67820c5fd2de641bc5e5e2bc3398075168c898ffaef42f7fa14cf3637962581047f93fb82eec3f683468b38fda401f23d9c5

test:
  secret_key_base: 6682fb27a50047ee003a0b02fe2eeb84a99b8c49d5eb0430e7cec23e43063016b603341fdb86447a16e3b6361e694ec7518ce0ab7a493d1bfc45d29124b7b63e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
